export type TurnStateType = 
  | "PLACE_REINFORCEMENTS"
  | "MOVEMENT_SELECTING_CELL"
  | "MOVEMENT_SELECTING_SOLDIER"
  | "SELECTING_MOVE"
  | "COMBAT_SELECTING_CELL"
  | "COMBAT_SELECTING_SOLDIER"
  | "SELECTING_COMBAT";

export const TURN_STATES = Object.freeze({
    PLACE_REINFORCEMENTS: "PLACE_REINFORCEMENTS" as TurnStateType,
  
    // Move Phase:
    MOVEMENT_SELECTING_CELL: "MOVEMENT_SELECTING_CELL" as TurnStateType,
    MOVEMENT_SELECTING_SOLDIER: "MOVEMENT_SELECTING_SOLDIER" as TurnStateType,
    SELECTING_MOVE: "SELECTING_MOVE" as TurnStateType,
  
    // Invasion Phase:
    COMBAT_SELECTING_CELL: "COMBAT_SELECTING_CELL" as TurnStateType,
    COMBAT_SELECTING_SOLDIER: "COMBAT_SELECTING_SOLDIER" as TurnStateType,
    SELECTING_COMBAT: "SELECTING_COMBAT" as TurnStateType,
});

